name: app_filmes
description: App Filmes.
publish_to: 'none'
# TODO: Bump to 2.0.0
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  firebase_remote_config: ^3.0.9
  flutter:
    sdk: flutter
  flutter_rating_stars: ^1.0.3+4
  flutter_signin_button: ^2.0.0
  get: ^4.6.5
  google_sign_in: ^5.4.3
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: FilmesAppIcons
      fonts:
        - asset: assets/fonts/FilmesAppIcons.ttf
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
        - asset: assets/fonts/metropolis/Metropolis-Semibold.otf
          weight: 600
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf
